/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create the Firestore document for a verified Firebase Auth user.
         *
         *     Stripe customer creation is deferred until checkout. The client creates
         *     the Auth user first, then calls this with its ID token. Idempotent.
         */
        post: operations["register_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signup-challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup Challenge
         * @description Exchange a successful Turnstile check for an email-bound signup proof.
         */
        post: operations["signup_challenge_v1_auth_signup_challenge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Checkout */
        post: operations["create_checkout_v1_billing_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plans
         * @description Public plan catalog for the pricing page. Price IDs match STRIPE_ENV.
         */
        get: operations["get_plans_v1_billing_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Portal */
        post: operations["create_portal_v1_billing_portal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Usage */
        get: operations["get_usage_v1_billing_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Demo Feed
         * @description Public demo summary (the default_user document), used by the marketing
         *     site and the logged-out preview.
         */
        get: operations["get_demo_feed_v1_demo_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feed */
        get: operations["get_feed_v1_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feed/source-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source Data */
        get: operations["get_source_data_v1_feed_source_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Generation */
        post: operations["start_generation_v1_generations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generation Cost */
        get: operations["generation_cost_v1_generations_cost_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Generation Status
         * @description The polling seam: reads the same pipeline_status document the pipeline
         *     writes stage transitions to.
         */
        get: operations["generation_status_v1_generations_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_v1_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Me
         * @description Delete the account: confirmation email, then Firebase Auth + Firestore
         *     (parity with the legacy profile delete flow).
         */
        delete: operations["delete_me_v1_me_delete"];
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_v1_me_patch"];
        trace?: never;
    };
    "/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_v1_settings_get"];
        /** Update Settings */
        put: operations["update_settings_v1_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Accounts */
        get: operations["get_accounts_v1_settings_accounts_get"];
        put?: never;
        /** Add Accounts */
        post: operations["add_accounts_v1_settings_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/accounts/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Accounts */
        post: operations["import_accounts_v1_settings_accounts_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/accounts/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Accounts */
        post: operations["verify_accounts_v1_settings_accounts_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/accounts/{handle}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Account */
        delete: operations["delete_account_v1_settings_accounts__handle__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountStat */
        AccountStat: {
            /** Account */
            account: string;
            /** Avg Likes */
            avg_likes: number;
            /** Avg Views */
            avg_views: number;
            /** Posts */
            posts: number;
        };
        /** AccountsResponse */
        AccountsResponse: {
            /** Accounts */
            accounts: string[];
            /** Max Accounts */
            max_accounts: number;
            /** Verified Accounts */
            verified_accounts: string[];
        };
        /** AddAccountsRequest */
        AddAccountsRequest: {
            /** Handles */
            handles: string[];
        };
        /** BillingUsageResponse */
        BillingUsageResponse: {
            credits: components["schemas"]["CreditState"];
            /** Plan */
            plan: string;
            usage: components["schemas"]["UsageCounts"];
        };
        /** ChatMessage */
        ChatMessage: {
            /** Content */
            content: string;
            /** Role */
            role: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
        };
        /** ChatResponse */
        ChatResponse: {
            credits: components["schemas"]["CreditState"];
            message: components["schemas"]["ChatMessage"];
        };
        /** CheckoutRequest */
        CheckoutRequest: {
            /** Price Id */
            price_id: string;
        };
        /** CreditState */
        CreditState: {
            /** Monthly Left */
            monthly_left: number;
            /** Monthly Limit */
            monthly_limit: number;
            /** Prepaid Left */
            prepaid_left: number;
            /** Prepaid Limit */
            prepaid_limit: number;
        };
        /** FeedResponse */
        FeedResponse: {
            /**
             * Audio Url
             * @default
             */
            audio_url: string;
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
            /**
             * Last Generation Time
             * @default
             */
            last_generation_time: string;
            /**
             * Last Generation Time Local
             * @default
             */
            last_generation_time_local: string;
            /**
             * Raw Data Sources
             * @default []
             */
            raw_data_sources: string[];
            /**
             * Summary Html
             * @default
             */
            summary_html: string;
            /**
             * Timezone
             * @default America/New_York
             */
            timezone: string;
        };
        /** GenerationCostResponse */
        GenerationCostResponse: {
            /**
             * Blockers
             * @default []
             */
            blockers: string[];
            /** Can Generate */
            can_generate: boolean;
            /** Cost */
            cost: number;
            credits: components["schemas"]["CreditState"];
        };
        /** GenerationStatus */
        GenerationStatus: {
            /**
             * Current Stage
             * @default
             */
            current_stage: string;
            /** End Time */
            end_time?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Stages Completed
             * @default []
             */
            stages_completed: string[];
            /** Start Time */
            start_time?: string | null;
            /**
             * Status
             * @default
             */
            status: string;
        };
        /** GlobalSettings */
        GlobalSettings: {
            /**
             * Ai Prompt
             * @default
             */
            ai_prompt: string;
            /**
             * Newsletter Email
             * @default
             */
            newsletter_email: string;
            /**
             * Timezone
             * @default America/New_York
             */
            timezone: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportAccountsRequest */
        ImportAccountsRequest: {
            /** Source */
            source: string;
        };
        /** ImportAccountsResponse */
        ImportAccountsResponse: {
            /** Accounts */
            accounts: string[];
            /** Imported */
            imported: string[];
            /**
             * Skipped Due To Limit
             * @default 0
             */
            skipped_due_to_limit: number;
        };
        /** MeResponse */
        MeResponse: {
            /**
             * Avatar
             * @default
             */
            avatar: string;
            /**
             * Created At
             * @default
             */
            created_at: string;
            credits: components["schemas"]["CreditState"];
            /** Email */
            email: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Onboarded
             * @default false
             */
            onboarded: boolean;
            /**
             * Onboarding Step
             * @default 0
             */
            onboarding_step: number;
            /** Plan */
            plan: string;
            plan_info: components["schemas"]["PlanInfo"];
            /**
             * Tos Accepted
             * @default false
             */
            tos_accepted: boolean;
            /** Uid */
            uid: string;
            usage: components["schemas"]["UsageCounts"];
        };
        /** Message */
        Message: {
            /** Detail */
            detail: string;
        };
        /** PlanInfo */
        PlanInfo: {
            /**
             * Cancel At Period End
             * @default false
             */
            cancel_at_period_end: boolean;
            /** Current Period End */
            current_period_end?: number | null;
            /** Current Period Start */
            current_period_start?: number | null;
            /** Period */
            period?: string | null;
            /** Status */
            status?: string | null;
        };
        /** PlanPublic */
        PlanPublic: {
            /** Id */
            id: string;
            /** Max Credits */
            max_credits: number;
            /** Max Followers */
            max_followers: number;
            /** Max Tweets Per Generation */
            max_tweets_per_generation: number;
            /** Price Id Month */
            price_id_month?: string | null;
            /** Price Id Year */
            price_id_year?: string | null;
            /** Price Month */
            price_month?: number | null;
            /** Price Year */
            price_year?: number | null;
        };
        /** PlansResponse */
        PlansResponse: {
            /** Plans */
            plans: components["schemas"]["PlanPublic"][];
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Avatar
             * @default
             */
            avatar: string;
            /**
             * Is Google Auth
             * @default false
             */
            is_google_auth: boolean;
            /**
             * Name
             * @default
             */
            name: string;
            /** Signup Challenge */
            signup_challenge?: string | null;
            /**
             * Tos Accepted
             * @default false
             */
            tos_accepted: boolean;
        };
        /** RegisterResponse */
        RegisterResponse: {
            /**
             * Already Registered
             * @default false
             */
            already_registered: boolean;
            /** Created */
            created: boolean;
        };
        /** SignupChallengeRequest */
        SignupChallengeRequest: {
            /** Email */
            email: string;
            /** Turnstile Token */
            turnstile_token?: string | null;
        };
        /** SignupChallengeResponse */
        SignupChallengeResponse: {
            /** Challenge Token */
            challenge_token: string;
        };
        /** SourceDataResponse */
        SourceDataResponse: {
            /** Per Account */
            per_account: components["schemas"]["AccountStat"][];
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Timeline */
            timeline: components["schemas"]["TimelinePoint"][];
            /** Total Likes */
            total_likes: number;
            /** Total Posts */
            total_posts: number;
            /** Total Views */
            total_views: number;
        };
        /** StartGenerationRequest */
        StartGenerationRequest: {
            /**
             * Fetch Latest
             * @default true
             */
            fetch_latest: boolean;
            /** Prompt */
            prompt?: string | null;
            /**
             * Skip Audio
             * @default false
             */
            skip_audio: boolean;
            /**
             * Skip Email
             * @default false
             */
            skip_email: boolean;
        };
        /** TimelinePoint */
        TimelinePoint: {
            /** Count */
            count: number;
            /** Time */
            time: string;
        };
        /** UpdateMeRequest */
        UpdateMeRequest: {
            /** Name */
            name?: string | null;
            /** Onboarded */
            onboarded?: boolean | null;
            /** Onboarding Step */
            onboarding_step?: number | null;
            /** Timezone */
            timezone?: string | null;
            /** Tos Accepted */
            tos_accepted?: boolean | null;
        };
        /** UpdateSettingsRequest */
        UpdateSettingsRequest: {
            /** Ai Prompt */
            ai_prompt?: string | null;
            /** Newsletter Email */
            newsletter_email?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** UrlResponse */
        UrlResponse: {
            /** Url */
            url: string;
        };
        /** UsageCounts */
        UsageCounts: {
            /**
             * N Chat Messages
             * @default 0
             */
            n_chat_messages: number;
            /**
             * N Followers Scraped
             * @default 0
             */
            n_followers_scraped: number;
            /**
             * N Generations
             * @default 0
             */
            n_generations: number;
            /**
             * N Newsletters Sent
             * @default 0
             */
            n_newsletters_sent: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerifyAccountsResponse */
        VerifyAccountsResponse: {
            /** Not Found */
            not_found: string[];
            /** Verified Accounts */
            verified_accounts: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    register_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_challenge_v1_auth_signup_challenge_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupChallengeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupChallengeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_checkout_v1_billing_checkout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plans_v1_billing_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlansResponse"];
                };
            };
        };
    };
    create_portal_v1_billing_portal_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_usage_v1_billing_usage_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingUsageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_v1_chat_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_demo_feed_v1_demo_feed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedResponse"];
                };
            };
        };
    };
    get_feed_v1_feed_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_data_v1_feed_source_data_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_generation_v1_generations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartGenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generation_cost_v1_generations_cost_get: {
        parameters: {
            query?: {
                fetch_latest?: boolean;
                skip_audio?: boolean;
            };
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationCostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generation_status_v1_generations_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_me_v1_me_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_v1_me_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_v1_settings_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_v1_settings_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_accounts_v1_settings_accounts_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_accounts_v1_settings_accounts_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddAccountsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_accounts_v1_settings_accounts_import_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportAccountsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportAccountsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_accounts_v1_settings_accounts_verify_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyAccountsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_v1_settings_accounts__handle__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
                "X-Firebase-AppCheck"?: string | null;
            };
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
